"""Lay the long voice-over take onto the 88 s timeline, sentence by sentence.

Cuts sit inside the pauses of the original take; sentences are placed on the music's
sections (hospitality lands in the quiet breakdown, the signature on the last crash).
Writes audio/vo.wav and src/timing.js (word timings on the final timeline).
"""
import json, subprocess
import numpy as np

SR, DUR = 48000, 88.0
SRC = "audio/raw/vo_long1.mp3"

# (key, cut-in, cut-out) on the original take → start on the final timeline
SENTENCES = [
    ("star",     0.00,  3.70,  2.30),
    ("since",    3.78, 12.40,  7.40),
    ("domestic", 12.58, 19.25, 17.30),
    ("regional", 19.40, 30.35, 25.30),
    ("fleet",    30.50, 38.60, 37.90),
    ("miles",    47.62, 57.70, 48.00),   # moved before hospitality
    ("cabin",    38.70, 47.45, 60.40),   # sits in the music breakdown
    ("booking",  57.90, 62.45, 70.60),
    ("signoff",  62.58, 66.00, 79.45),   # "Camair-Co." on the final crash
]

raw = subprocess.run(["ffmpeg", "-v", "error", "-i", SRC, "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
                     capture_output=True, check=True).stdout
x = np.frombuffer(raw, np.float32)
y = np.zeros(int(DUR * SR), np.float32)
ramp = np.linspace(0, 1, 480, dtype=np.float32)
for _, a, b, at in SENTENCES:
    seg = x[int(a * SR):int(b * SR)].copy()
    seg[:480] *= ramp; seg[-480:] *= ramp[::-1]
    i = int(at * SR); y[i:i + len(seg)] += seg

subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", "1", "-i", "-", "audio/vo.wav"],
               input=y.tobytes(), check=True)

words = json.load(open("audio/raw/vo_long1_words.json"))["words"]
out, sections = [], {}
for key, a, b, at in SENTENCES:
    sections[key] = round(at + 0.0, 3)
    for w in words:
        if w["type"] == "word" and a <= w["start"] < b and w["text"].strip(":"):
            out.append({"w": w["text"], "s": round(at + w["start"] - a, 3), "e": round(at + w["end"] - a, 3), "k": key})
with open("src/timing.js", "w") as f:
    f.write("// generated by scripts/place_vo.py — voice-over word timings on the final 88 s timeline\n")
    f.write("window.VO = " + json.dumps({"sections": sections, "words": out}, ensure_ascii=False) + ";\n")
for wd in out:
    print(f'{wd["s"]:6.2f}-{wd["e"]:6.2f} {wd["k"]:9s} {wd["w"]}')
